name: Gambit - CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - github-actions # TODO: Remove this before enabling on Gambit repo

jobs:
  Debug:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: I like to fail
        run: exit 1
        # run: echo "But not this time!"
      - name: Report Failure to Gitter
        run: curl --data-urlencode "message=${{ github.job }} build of run [$GITHUB_RUN_ID](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) failed" -d level=error ${{ secrets.GITTER_URL }}
        if: ${{ failure() }}

  Job2:
    runs-on: ubuntu-latest
    steps:
      - name: I like to pass
        run: echo "It's all good"

  ReportResult:
    runs-on: ubuntu-latest
    needs: [Job1, Job2]
    if: ${{ success() }}

    steps:
    - name: Report Success to Gitter
      run: curl --data-urlencode "message=CI run [$GITHUB_RUN_ID](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) passed" ${{ secrets.GITTER_URL }}
      if: ${{ success() }}
