name: Gambit - CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - github-actions # TODO: Remove this before enabling on Gambit repo

jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - name: I like to fail
        run: exit 1

  Job2:
    runs-on: ubuntu-latest
    steps:
      - name: I like to pass
        run: echo "It's all good"

  ReportResult:
    runs-on: ubuntu-latest
    needs: [Job1, Job2]
    if: ${{ github.event_name == 'pull_request' }}

    steps:
    - name: Report Success to Gitter
      run: curl --data-urlencode "message=GitHub Actions CI run [#${{ github.run_id }}](https://github.com/gambit/gambit/actions/runs/${{ github.run_id }}) passed" ${{ secrets.GITTER_URL }}
      if: ${{ success() }}

    - name: Report Failure to Gitter
      run: curl --data-urlencode "message=GitHub Actions CI run [#${{ github.run_id }}](https://github.com/gambit/gambit/actions/runs/${{ github.run_id }}) failed" -d level=error ${{ secrets.GITTER_URL }}
      if: ${{ failure() }}
